### ISSUE TITLE
Pad projections/filters to power of 2

### ISSUE THREAD

**Issue by FreeCT** [FreeCT/FreeCT#5]
Improve efficiency of filter operation

**Comment by johnmarianhoffman** [comment]
This should actually be benchmarked before committing to it.  Some simple matlab tests (NOT GPU-based though) showed that the padding+unpadding overhead was not worth it for FFTs of the size we're working with.

**Comment by johnmarianhoffman** [comment]
Additionally, we need to pad the projections to limit interference/wrap-around artifacts.

**Comment by johnmarianhoffman** [comment]
Issue fixed by doubling padding out to double the number of channels, then rounding up to the next power of two.
